### ISSUE TITLE
Remove `sphinx-needs` plugin

### ISSUE THREAD

**Issue by redeboer** [ComPWA/compwa-org#209]
```[tasklist]
### Tasks
- [x] Remove `pr` and `issue` roles (does not work well with `jupyterlab-myst`)
- [x] Remove `sphinx_issues` plugin
- [x] Replace all `need` roles with `doc` links
- [x] Convert all `spec` directives to [`card`](https://sphinx-design.readthedocs.io/en/latest/cards.html)
- [x] Add links to related PRs and issues in card footer
- [x] Convert `sphinx-needs` tags to cell tags of the card cell. These will be used by the script that create a DataTable of reports.
- [x] Remove `sphinx-needs`
- [x] Convert [`needtable`](https://github.com/ComPWA/compwa-org/blob/cf9e1ad31787039fcfa2e520665028fd75a6a0a4/docs/reports.md#L10-L13) to data table generated by script. See [here](https://raw.githubusercontent.com/executablebooks/meta/0377df63f5f95630488c44d0b1cf531161485531/docs/feature-vote.md) for inspiration
```

> ### Original post
> The problem seems to be caused by [`sphinx-needs`](https://sphinx-needs.readthedocs.io), which we use to structure and interlink the technical reports (e.g. the table at [compwa-org.rtfd.io/reports.html](https://compwa-org.rtfd.io/reports.html)). Once the `sphinx_needs` extension has been disabled (564e827), Plotly figures are visible again (removing any `need` or `spec` directives from the notebook also does not fix the problem).
> 
> An alternative for organizing report notebooks may be [`sphinx-gallery`](https://sphinx-gallery.github.io), but this [does not seem to work well with MyST-NB](https://github.com/executablebooks/MyST-NB/issues/396). Ideally, we want to have something like [learn.astropy.org](https://learn.astropy.org), where you can search for notebooks with filters etc. 
> 
> Some alternatives:
> - Write some script that creates a [DataTable](https://datatables.net) from the TR notebooks, just like EBP's [feature vote](https://executablebooks.org/en/latest/feature-vote).
> - ~[ablog.rtfd.io](https://ablog.readthedocs.io)~
>   No longer actively maintained
> - ~[learn.astropy.org](https://learn.astropy.org)~
>   Looks best, but we would have to Gatsby, a whole different ecosystem than Sphinx
> _Originally posted by @redeboer in https://github.com/ComPWA/compwa-org/issues/206#issuecomment-1734337843_
